name: Runs CodeQL
description: |
  Runs all CodeQL necessary actions to scan and upload the result to Github

inputs:
  auto-build:
    description: Use CodeQL's auto-build.
    required: false
    default: "false"
  build-script:
    description: Optional path to an executable file that will perform a full, uncached, build for CodeQL analysis.
    required: false
  languages:
    description: The languages of the checks to run, separated by a comma. Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support.
    required: true
  category:
    description: String used by Code Scanning for matching the analyses.
    required: false
  working-directory:
    description: Relative path under $GITHUB_WORKSPACE where the root project is located.
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Write CodeQL config file
      id: config
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        buildDir=$(realpath ./build)
        configFile="${buildDir}/codeqlconfig.yaml"
        mkdir -p "$buildDir"
        cat > "$configFile" <<EOF
        paths:
          - $(pwd)
        queries:
          - uses: security-extended
        EOF
        echo "config-file=$configFile" >> $GITHUB_OUTPUT

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        config-file: ${{ steps.config.outputs.config-file }}
        languages: ${{ inputs.languages }}

    - if: inputs.auto-build == 'true'
      name: Auto-build
      uses: github/codeql-action/autobuild@v2

    - name: Execute build script
      if: inputs.build-script != ''
      env:
        BUILD_SCRIPT: ${{ inputs.build-script }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: exec "$(realpath "$BUILD_SCRIPT")"

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: ${{ inputs.category }}
